USE MeshliumDB;

DROP PROCEDURE IF EXISTS USP_GET_AVG_WATERFLOW;
DELIMITER //
CREATE PROCEDURE USP_GET_AVG_WATERFLOW()
BEGIN


DECLARE AVG_FLOW decimal(10,3);

SELECT 
	avg(value) 
FROM sensorParser 
WHERE sensor='WF' 
	AND value <> 0 
    AND timestamp BETWEEN DATE_SUB(UTC_TIMESTAMP(), INTERVAL 1 WEEK) AND UTC_TIMESTAMP()
INTO AVG_FLOW;

SELECT IF (AVG_FLOW is NOT NULL, AVG_FLOW, 0) as AverageFlow;

END
//
DELIMITER ;