USE MeshliumDB;

DROP PROCEDURE IF EXISTS USP_SAVE_ET0VALUE;
DELIMITER //
CREATE PROCEDURE USP_SAVE_ET0VALUE(
 IN `value` varchar(50)
)
BEGIN


INSERT INTO `EVAPOTRANSPIRATIONDATA`( ET0_value, dateInserted) values (`value`, UTC_TIMESTAMP());


END
//
DELIMITER ;