USE MeshliumDB;

DROP PROCEDURE IF EXISTS USP_GET_ET0VALUE;
DELIMITER //
CREATE PROCEDURE USP_GET_ET0VALUE()
BEGIN


select ET0_value from `EVAPOTRANSPIRATIONDATA`order by dateInserted DESC limit 1;


END
//
DELIMITER ;